"""Conversation-summary inputs and evidence-backed outputs."""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from irya_ai.schemas.analysis import QAPair
from irya_ai.schemas.base import CamelModel
from irya_ai.schemas.transcript import SpeakerRole, TranscriptStage


class DraftModel(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


class CitationDraft(DraftModel):
    utterance_id: str
    quote: str


class PointDraft(DraftModel):
    text: str
    citations: list[CitationDraft]


class SummaryDraft(DraftModel):
    """Only claims and verbatim quotations are generated by the model."""

    points: list[PointDraft]


class Evidence(CamelModel):
    utterance_id: str
    quote: str
    speaker: SpeakerRole
    start_ms: int
    end_ms: int


class SummaryPoint(CamelModel):
    text: str
    evidence: list[Evidence]


class SummaryResult(CamelModel):
    session_id: str
    summary: str
    key_points: list[str] = Field(default_factory=list)
    source_utterance_ids: list[str] = Field(default_factory=list)
    model: str
    points: list[SummaryPoint] = Field(default_factory=list)
    rejected_point_count: int = 0


class AnalysisError(CamelModel):
    code: str
    retryable: bool


class AnalysisResult(CamelModel):
    session_id: str
    transcript_stage: TranscriptStage
    status: Literal["completed", "partial", "failed", "empty"]
    qa_pairs: list[QAPair]
    unpaired_utterance_ids: list[str]
    summary_result: SummaryResult | None = None
    warnings: list[str] = Field(default_factory=list)
    error: AnalysisError | None = None
    elapsed_ms: int = 0
